### ISSUE TITLE
Cannot make it to work with Gimp 2.10

### ISSUE THREAD

**Issue by doragasu** [flamewing/mdcolors#3] opened 2020-03-22 09:12 UTC
I am running Archlinux, and I have Python 2.7 and `enum34` package for Python 2 installed.

I have read that RGB mode does not work with Gimp 2.10, but I cannot make it to work even with indexed color.

I have tried both installing the plugin under `~/.gimp-2.10/plug-ins` and `/usr/lib/gimp/2.0/plug-ins`, but the `Mega Drive` option does never appear under `Filters` menu.

I have also tried changing the shebang to `#!/usr/bin/env python2.7` (since Archlinux defaults to Python 3), but it didn't help. Also tried refreshing the plugins list inside Gimp. No luck.

**Comment by flamewing** [comment] 2020-03-22 09:56
Can you put a list of the plugin directories (Preferences -> Folders -> Plug-ins) here? Also, can you try starting Gimp from the command line and see if there is anything relevant in the logs?

**Comment by doragasu** [comment] 2020-03-23 08:14
I tried starting it from the command line, and it showed nothing. Then had a look to the plugins path and found this:
```
/home/jalon/.config/GIMP/2.10/plug-ins
/usr/lib/gimp/2.0/plug-ins
```
Moved the plugin to `~/.config/GIMP/2.10/plug-ins`, and did not work, but now launching GIMP from the CLI shows the problem:

```
jalon ~ $ gimp
Traceback (most recent call last):
  File "/home/jalon/.config/GIMP/2.10/plug-ins/mdcolors.py", line 24, in <module>
    from gimpfu import gimp
ImportError: No module named gimpfu
gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error
```

**Comment by doragasu** [comment] 2020-03-23 08:32
It seems `gimpfu.py` was removed from the GIMP package. It looks to me as an Archlinux packaging error. I was using latest Archlinux version 2.10.18-4. Downgraded to 2.10.18-2, and now the plugin shows in the menu!

I will open a bug on the Arch bugtracker. I think this can be closed.

Thanks!

**Comment by flamewing** [comment] 2020-03-23 08:36
I had come to the same conclusion, and was about to post something to that effect. Though it is likely that they will close it as a "won't fix", because it seems a deliberate choice (see [this bug report for Gimp](https://gitlab.gnome.org/GNOME/gimp/issues/4826). Anyway, closing this due to it being caused by packager idiocy.

**Closed as completed by flamewing** 2020-03-23 08:36 UTC

**Comment by doragasu** [comment] 2020-03-23 08:39
Then the removal is deliberate, too bad!. No bug report then. Thanks for the info!

**Comment by flamewing** [comment] 2020-03-23 08:42
You might as well try; maybe if enough people complain they will revisit the decision. Maybe.

**Comment by doragasu** [comment] 2020-03-23 09:18
Well, they were the first (along with Fedora) to switch to systemd. I do not think they are going back on this...
